// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"week04/internal/biz"
	"week04/internal/data"
)

// Injectors from wire.go:

func InitUserBiz(str string) *biz.UserBiz {
	db := data.NewDB(str)
	userRepo := data.NewUserRepo(db)
	userBiz := biz.NewUserBiz(userRepo)
	return userBiz
}
